### ISSUE TITLE
Error showing preview katex in EditorMD

### ISSUE THREAD

**Issue by buiphukhuyen** [SCNU-SoCoding/scnuoj#113]
Hi,
When using bullet, katex doesn't work in EditorMD preview, do you have a solution to this problem?

<img width="500" alt="Screenshot 2022-12-13 at 21 10 44" src="https://user-images.githubusercontent.com/43597300/207355937-2c99adf5-f2f3-4f98-a69b-3b292ad2e2d5.png">
<img width="500" alt="Screenshot 2022-12-13 at 21 10 52" src="https://user-images.githubusercontent.com/43597300/207355947-0a65d9e5-37ed-4aaa-8519-2919343e544f.png">

**Comment by bobby285271** [comment]
(也可以说中文，如果交流起来更方便的话)

FYI, this is how other places handle inline latex:
https://github.com/scnu-socoding/scnuoj/blob/d19f5001696161fe440f7a1a2b4b9cd779f7c46f/components/Formatter.php#L72-L83

I haven't actually tested this yet, but looking at https://github.com/scnu-socoding/scnuoj/blob/d19f500/widgets/editormd/assets/editormd.js#L3599, I guess editormd should probably treat `$\text{this}$` as valid inline latex instead.

And `$$\text{this}$$` should be something that should be rendered as block latex.

![2022-12-13 23-00-28屏幕截图](https://user-images.githubusercontent.com/20080233/207368751-85b1f5a8-0cde-4aac-8f32-42d51371f0e5.png)
![2022-12-13 23-00-06屏幕截图](https://user-images.githubusercontent.com/20080233/207368772-5e97039d-8fac-4a1a-8693-95c5f5ec9c74.png)

**Comment by buiphukhuyen** [comment]
我修改了 editormd.js 文件以匹配 `$\text{this}$`。 但是，当使用项目符号（没有 2 行分隔符）时，EditorMD 的 Katex 预览无法正确显示。 （同样在 components/Formatter.php 它仍然可以正常工作）

<img width="755" alt="Screenshot 2022-12-13 at 22 31 13" src="https://user-images.githubusercontent.com/43597300/207376196-c425c732-0ce0-42e6-b7e7-19799340219e.png">

<img width="892" alt="Screenshot 2022-12-13 at 22 29 10" src="https://user-images.githubusercontent.com/43597300/207376231-1a3acaf2-7387-4fdc-a89d-efd1571740fd.png">
