### ISSUE TITLE
错误格式 json checker_log Java/Python语言

### ISSUE THREAD

**Issue by buiphukhuyen** [SCNU-SoCoding/scnuoj#118]
运行judge时，部分测试用例如果运行失败，由于json存储结构不正确，不会显示错误详情。 你如何解决这个错误？ 非常感谢你！

<img width="1428" alt="Screenshot 2023-01-20 at 22 54 21" src="https://user-images.githubusercontent.com/43597300/213745470-3d12cb1a-d1e8-416c-86a4-c4475e2c78aa.png">

**Comment by buiphukhuyen** [comment]
是的，我通过这样的 js 语法修复了它！ 谢谢，请允许我关闭问题！
<img width="493" alt="Screenshot 2023-01-21 at 00 11 32" src="https://user-images.githubusercontent.com/43597300/213761534-0333e053-f668-41d1-9269-df99aae08c06.png">

**Comment by bobby285271** [comment]
嗯这个地方我也很头疼，目前来看好像只能 case by case 地处理 :upside_down_face:
