### ISSUE TITLE
判题时遇到一点问题想请问一下

### ISSUE THREAD

**Issue by jiuxiajingfan** [scnu-socoding/scnuoj#33]
打扰了
在判题时交c++和c 不管用scanf或是cout判题都显示无输出 不知大概是哪里出了问题
其他语言倒是不会有这个问题

![QQ图片20210709164031](https://user-images.githubusercontent.com/69376042/125050356-796ff100-e0d4-11eb-8389-4b19416169ff.jpg)
![QQ图片20210709164037](https://user-images.githubusercontent.com/69376042/125050365-7bd24b00-e0d4-11eb-9916-b1062d4dcbaa.jpg)

**Comment by bobby285271** [comment]
// 呀，这个 OJ 没想到有非 SCNUer 用的...

在终端分别执行一下  `gcc --version` 和 `g++ --version`，如果是 `command not found` 我刚刚试了一下会出现跟上面一样的情况。

如果是 `command not found`，先看看有没有装 GCC，然后看看命令名称是不是 `gcc` 和  `g++`，如果不是的话去编辑 `judge/src/language.h` 改成正确的命令，然后杀掉判题机重新编译再重新启动判题机再重判。

// 文档好像确实没说编译器安装的事，找个时间补充一下。

如果上面两个命令都存在，那么先把判题机杀了，然后 `./dispatcher -d` 然后去交一发看看终端有没有什么奇怪的输出？

**Comment by jiuxiajingfan** [comment]
已解决 感谢
