### ISSUE TITLE
比赛罚时自定义

### ISSUE THREAD

**Issue by bobby285271** [scnu-socoding/scnuoj#39]
看看能不能把 AK 杯的罚时调为 10 分钟（甚至 5 分钟）...
20 分钟对于三小时拼手速比赛来说太狠了

cc @scnu-socoding/shannon

**Comment by M1saka10010** [comment]
自问自答是吧，不过墙裂支持

**Comment by bobby285271** [comment]
不我把锅甩给 20 级的几位了，~~搞不出来另说~~

**Comment by lr580** [comment]
照现状而言搞不出来的概率可能更高qwq(

**Comment by M1saka10010** [comment]
你们是住在Github的吗？ @bobby285271 @lr580

**Comment by bobby285271** [comment]
还是我自己来吧... @lr580 其实就差了一个 [migration](https://www.yiiframework.com/doc/guide/2.0/en/db-migrations)，加上了就好了

**Comment by lr580** [comment]
我太菜了qwq 勉强看完了php,sql和yii教程还是没看懂那个save怎么改才能保存好自定义编辑的罚时

**Comment by lr580** [comment]
> 我太菜了qwq 勉强看完了php,sql和yii教程还是没看懂那个save怎么改才能保存好自定义编辑的罚时

所以save是不用改的吗
