### ISSUE TITLE
求一键部署脚本

### ISSUE THREAD

**Issue by xiejin1211** [SCNU-SoCoding/scnuoj#98]
根据安装教程部署了很多次都没有成功，求一键部署的脚本。

**Comment by bobby285271** [comment]
emmm... 那个安装教程也有一段时间没有验证过了，我看看有没有时间吧，长远来看如果能把网页和判题机打成 docker 镜像再提供一个 docker-compose.yaml 肯定是最好的，或者你也可以先说说你哪步出了问题😂

**Comment by xiejin1211** [comment]
composer install这一步下不去了，安装了composer 的，反正各种报错，一直百度折腾，求一键安装。

**Comment by M1saka10010** [comment]
> composer install这一步下不去了，安装了composer 的，反正各种报错，一直百度折腾，求一键安装。

php版本多少，7.4实测没问题

**Comment by xiejin1211** [comment]
这次使用了PHP7.4，让然卡在composer install，求一键安装

**Comment by M1saka10010** [comment]
> 这次使用了PHP7.4，让然卡在composer install，求一键安装

请提供报错

**Comment by xiejin1211** [comment]
非常感谢协助，前后折腾了好几次了，始终卡在这一步，我php版本是7.4，其他的插件也全部安装了的

&nbsp;


谢进
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月1日(星期四) 下午5:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [scnu-socoding/scnuoj] 求一键部署脚本 (Issue #98)





  
这次使用了PHP7.4，让然卡在composer install，求一键安装
  
请提供报错

**Comment by xiejin1211** [comment]
非常感谢协助，前后折腾了好几次了，始终卡在这一步，我php版本是7.4，其他的插件也全部安装了的.

ssh地址：117.187.17.86:22223&nbsp;用户：xiejin&nbsp;密码：xiejin，
&nbsp;


谢进
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月1日(星期四) 下午5:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [scnu-socoding/scnuoj] 求一键部署脚本 (Issue #98)





  
这次使用了PHP7.4，让然卡在composer install，求一键安装
  
请提供报错

**Comment by xiejin1211** [comment]
好像图片发不了

**Comment by xiejin1211** [comment]
这样的。


谢进
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "scnu-socoding/scnuoj"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月1日(星期四) 下午5:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [scnu-socoding/scnuoj] 求一键部署脚本 (Issue #98)





  
这次使用了PHP7.4，让然卡在composer install，求一键安装
  
请提供报错

**Comment by xiejin1211** [comment]
- Installing bower-asset/inputmask (3.3.11): Downloading (failed)       
Downloading (failed)       
Downloading (failed)    Failed to download bower-asset/inputmask from dist: The "https://api.github.com/repos/RobinHerbots/Inputmask/zipball/5e670ad62f50c738388d4dcec78d2888505ad77b" file could not be downloaded: SSL: Connection reset by peer
Failed to enable crypto
failed to open stream: operation failed

**Comment by M1saka10010** [comment]
> * Installing bower-asset/inputmask (3.3.11): Downloading (failed)
>   Downloading (failed)
>   Downloading (failed)    Failed to download bower-asset/inputmask from dist: The "https://api.github.com/repos/RobinHerbots/Inputmask/zipball/5e670ad62f50c738388d4dcec78d2888505ad77b" file could not be downloaded: SSL: Connection reset by peer
>   Failed to enable crypto
>   failed to open stream: operation failed

这是你本地网络的问题，可以尝试使用代理或者更换源服务器

**Comment by xiejin1211** [comment]
阿里的镜像源，每一次安装到composer install就完全下不去了。
&nbsp;


谢进
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月5日(星期一) 晚上11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [scnu-socoding/scnuoj] 求一键部署脚本 (Issue #98)





   
Installing bower-asset/inputmask (3.3.11): Downloading (failed)
 Downloading (failed)
 Downloading (failed)    Failed to download bower-asset/inputmask from dist: The "https://api.github.com/repos/RobinHerbots/Inputmask/zipball/5e670ad62f50c738388d4dcec78d2888505ad77b" file could not be downloaded: SSL: Connection reset by peer
 Failed to enable crypto
 failed to open stream: operation failed
   
这是你本地网络的问题，可以尝试使用代理或者更换源服务器

**Comment by M1saka10010** [comment]
> * Installing bower-asset/inputmask (3.3.11): Downloading (failed)
>   Downloading (failed)
>   Downloading (failed)    Failed to download bower-asset/inputmask from dist: The "https://api.github.com/repos/RobinHerbots/Inputmask/zipball/5e670ad62f50c738388d4dcec78d2888505ad77b" file could not be downloaded: SSL: Connection reset by peer
>   Failed to enable crypto
>   failed to open stream: operation failed

已完成 Docker 化，可使用 Docker 部署
